const letterRules = {
  m: [
    { start: "p1", end: "p2" },
    { start: "p1", end: "p4" },
    { start: "p2", end: "p3" },
    { start: "p2", end: "p5" },
    { start: "p3", end: "p6" },
    { start: "p4", end: "p7" },
    { start: "p5", end: "p8" },
    { start: "p6", end: "p9" },
  ],
  o: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p4", end: "p1" },
    { start: "p4", end: "p7" },
    { start: "p6", end: "p3" },
    { start: "p6", end: "p9" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p9" }
  ],
  a: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p3", end: "p6" },
    { start: "p4", end: "p5" },
    { start: "p4", end: "p7" },
    { start: "p5", end: "p6" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p9" },
    { start: "p9", end: "p6" },
  ],
  b: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p3", end: "p6" },
    { start: "p1", end: "p4" },
    { start: "p1", end: "p4" },
    { start: "p4", end: "p5" },
    { start: "p5", end: "p6" },
    { start: "p4", end: "p7" },
    { start: "p2", end: "p3" },
    { start: "p6", end: "p9" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p9" },
  ],
  r: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p1", end: "p4" },
    { start: "p4", end: "p7" },
  ],
  n: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p1", end: "p4" },
    { start: "p3", end: "p6" },
    { start: "p4", end: "p7" },
    { start: "p6", end: "p9" },
  ],
  s: [
    { start: "p1", end: "p2" },
    { start: "p1", end: "p4" },
    { start: "p2", end: "p3" },
    { start: "p4", end: "p5" },
    { start: "p5", end: "p6" },
    { start: "p6", end: "p9" },
    { start: "p8", end: "p9" },
    { start: "p8", end: "p7" },
  ],
  t: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p3" },
    { start: "p2", end: "p5" },
    { start: "p5", end: "p8" },
    { start: "p8", end: "p9" },
  ],
  p: [
    { start: "p1", end: "p2" },
    { start: "p1", end: "p4" },
    { start: "p3", end: "p6" },
    { start: "p2", end: "p3" },
    { start: "p4", end: "p5" },
    { start: "p5", end: "p6" },
    { start: "p4", end: "p7" },
  ],
  e: [
    { start: "p1", end: "p2" },
    { start: "p1", end: "p4" },
    { start: "p2", end: "p3" },
    { start: "p3", end: "p6" },
    { start: "p4", end: "p7" },
    { start: "p4", end: "p5" },
    { start: "p5", end: "p6" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p9" },
  ],
  d: [
    { start: "p1", end: "p2" },
    { start: "p2", end: "p6" },
    { start: "p1", end: "p4" },
    { start: "p4", end: "p7" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p6" },
  ],
  u: [
    { start: "p1", end: "p4" },
    { start: "p4", end: "p7" },
    { start: "p7", end: "p8" },
    { start: "p8", end: "p9" },
    { start: "p3", end: "p6" },
    { start: "p6", end: "p9" },
  ],
  j: [
    { start: "p2", end: "p3" },
    { start: "p3", end: "p6" },
    { start: "p6", end: "p9" },
    { start: "p9", end: "p8" },
    { start: "p7", end: "p8" },
    { start: "p4", end: "p7" },
  ]
}